package com.example.accessingdatamysql.controllers;

import com.example.accessingdatamysql.dao.*;
import com.example.accessingdatamysql.models.*;
import com.google.common.hash.Hashing;
import io.swagger.annotations.Api;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.util.DigestUtils;
import org.springframework.web.bind.annotation.*;

import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
@Api(value = "asdas", description = "Controller")
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private AddressRepository addressRepository;
    @Autowired
    private PostalRepository postalRepository;
    @Autowired
    private ProductRepository productRepository;
    @Autowired
    private CategoryRepository categoryRepository;
    @Autowired
    private CardRepository cardRepository;


    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestBody User user) {


        User user1 = userRepository.findUserByEmail(user.getEmail());


        if(user1!= null)
            return "This mail is already in use";

        String passSha;
        String pass;
        if(user.getPassword() != null)
            pass = user.getPassword();
        else return "pass";

        passSha = Hashing.sha256().hashString(user.getPassword(), StandardCharsets.UTF_8).toString();
        user.setPassword(passSha);


        userRepository.save(user);
        return "Saved";
    }

    @PostMapping(path= "updateUser")
    public @ResponseBody String updateUser (@RequestBody User user) {

        User user1 = userRepository.findUserByEmail(user.getEmail());

        if(user1 == null)
            return "Requested User not found";

        for(Address a: user.getAddresses())
        {
            PostalCode postalCode = postalRepository.findByPostalCode(a.getPostalCode().getPostalCode());
            if(postalCode != null)
            {
                a.setPostalCode(postalCode);
            }
            user1.getAddresses().add(a);
        }

        Set<CardInfo> cards = new HashSet<>();
        for(CardInfo c: user.getCards()){

            Set<User> s = new HashSet<User>();
            s.add(user1);
            c.setUsers(s);
            cards.add(c);
        }
        if(user.getPassword() != null)
        {
            String passSha = Hashing.sha256().hashString(user.getPassword(), StandardCharsets.UTF_8).toString();
            user1.setPassword(passSha);
        }
        user1.setCards(cards);
        userRepository.save(user1);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {

        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
    @GetMapping(path="/alladdress")
    public @ResponseBody Iterable<Address> getAllAddress() {
        // This returns a JSON or XML with the users
        return addressRepository.findAll();
    }
    @PostMapping(path="/login")
    public @ResponseBody String login(@RequestParam String email, @RequestParam String password) {
        User user;

        user = userRepository.findUserByEmail(email);
        if(user == null){
            return "Incorrect email";
        }
        if(user.getPassword().equals(Hashing.sha256().hashString(password,StandardCharsets.UTF_8).toString())){
            return "Logged In";
        }
        else {
            return "Incorrect Password";
        }
    }
    @PostMapping(path= "/addSellerAddress")
    public @ResponseBody String addSellerAddress(@RequestParam Integer userID, @RequestParam String addressName){
            User user = userRepository.findUserByUserID(userID);
            if(user == null){
                return "Requested user not found";
            }

            Address address = new Address();
            //Address[] addresses = user.getAddresses();
            boolean found = false;
            for(Address a:user.getAddresses()){
                if(addressName.equals(a.getAddressName()))
                {
                    address.setAddressID(a.getAddressID());
                    found = true;
                }
            }
            if(!found)
                return "address not found";

            user.setSellerAddressID(address);

            userRepository.save(user);
            return "saved";
    }
    @PostMapping(path= "/addAddress")
    public @ResponseBody String addAddress(@RequestParam Integer userID, @RequestBody Address address){
        User user = userRepository.findUserByUserID(userID);
        if(user == null){
            return "Requested user not found";
        }

        addressRepository.save(address);

        user.getAddresses().add(address);
        userRepository.save(user);
        return "saved";
    }
    @PostMapping(path ="/addBook")
    public @ResponseBody String addBook(@RequestParam Integer sellerID, @RequestBody Product product)
    {
        productRepository.save(product);
        return "seller Not Implemented, added book";
    }

    @PostMapping(path = "/addCategory") // Admin
    public @ResponseBody String addCategory(@RequestParam String name)
    {
        Category category = new Category(name);
        categoryRepository.save(category);
        return "Category Saved";
    }
    /*
    @PostMapping(path="/addpostal")
    public @ResponseBody String addPostal(@RequestBody PostalCode postalCodeCity){
        postalRepository.save(postalCodeCity);
        return "saved";
    }*/
}